// Starter content for the three card types, used by prisma/seed.ts to build
// the public "Angielski od podstaw" decks. Kept as TypeScript rather than
// JSON so the level/type values are checked at build time and the Polish
// explanations can carry comments.

export type StarterLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1';

export interface StarterCard {
  /** Card front: the word for vocabulary, the rule's name for grammar/tenses. */
  word: string;
  /** English definition or the grammatical formula. */
  meaningEn: string | null;
  translationPl: string | null;
  exampleSentence: string | null;
  /** Longer Polish explanation shown under the answer. */
  explanation: string | null;
  partOfSpeech: string | null;
  level: StarterLevel;
}

export const STARTER_VOCABULARY: StarterCard[] = [
  {
    word: 'to be',
    meaningEn: 'to exist or to have a particular quality or identity',
    translationPl: 'być',
    exampleSentence: 'I am a student.',
    explanation: 'Najważniejszy czasownik w angielskim. Formy: I am, you are, he/she/it is, we/you/they are.',
    partOfSpeech: 'verb',
    level: 'A1',
  },
  {
    word: 'to have',
    meaningEn: 'to own or possess something',
    translationPl: 'mieć',
    exampleSentence: 'I have a car.',
    explanation: 'W 3. osobie liczby pojedynczej przyjmuje formę "has": he has, she has, it has.',
    partOfSpeech: 'verb',
    level: 'A1',
  },
  {
    word: 'to do',
    meaningEn: 'to perform an action or task',
    translationPl: 'robić',
    exampleSentence: 'I do my homework every evening.',
    explanation: 'Pełni też funkcję operatora w pytaniach i przeczeniach: "Do you work?", "I do not work".',
    partOfSpeech: 'verb',
    level: 'A1',
  },
  {
    word: 'to go',
    meaningEn: 'to move or travel from one place to another',
    translationPl: 'iść, jechać',
    exampleSentence: 'I go to school by bus.',
    explanation: 'Czasownik nieregularny: go - went - gone.',
    partOfSpeech: 'verb',
    level: 'A1',
  },
  {
    word: 'to eat',
    meaningEn: 'to put food in your mouth and swallow it',
    translationPl: 'jeść',
    exampleSentence: 'I eat breakfast at seven.',
    explanation: 'Czasownik nieregularny: eat - ate - eaten.',
    partOfSpeech: 'verb',
    level: 'A1',
  },
  {
    word: 'appointment',
    meaningEn: 'an arrangement to meet someone at a particular time',
    translationPl: 'spotkanie, wizyta',
    exampleSentence: 'I have a doctor appointment at noon.',
    explanation: 'Dotyczy spotkań umówionych wcześniej - u lekarza, u fryzjera, w urzędzie.',
    partOfSpeech: 'noun',
    level: 'A2',
  },
  {
    word: 'available',
    meaningEn: 'free to be used, or able to meet someone',
    translationPl: 'dostępny',
    exampleSentence: 'Are you available tomorrow?',
    explanation: 'Mówi się o osobach (mających czas) i o rzeczach (będących w sprzedaży, na stanie).',
    partOfSpeech: 'adjective',
    level: 'A2',
  },
  {
    word: 'to improve',
    meaningEn: 'to make something better, or to become better',
    translationPl: 'poprawiać, ulepszać',
    exampleSentence: 'I want to improve my English.',
    explanation: 'Rzeczownik: improvement (poprawa). Przyimek: improve AT something.',
    partOfSpeech: 'verb',
    level: 'A2',
  },
  {
    word: 'experience',
    meaningEn: 'knowledge or skill gained from doing something',
    translationPl: 'doświadczenie',
    exampleSentence: 'I have five years of work experience.',
    explanation: 'Niepoliczalny w znaczeniu "doświadczenie zawodowe", policzalny jako "przeżycie": a strange experience.',
    partOfSpeech: 'noun',
    level: 'A2',
  },
  {
    word: 'to decide',
    meaningEn: 'to choose something after thinking about it',
    translationPl: 'decydować',
    exampleSentence: 'I decided to learn English.',
    explanation: 'Konstrukcja: decide TO DO something albo decide ON something. Rzeczownik: decision.',
    partOfSpeech: 'verb',
    level: 'A2',
  },
  {
    word: 'to achieve',
    meaningEn: 'to successfully reach a goal after effort',
    translationPl: 'osiągnąć',
    exampleSentence: 'She achieved her goal after two years.',
    explanation: 'Łączy się z celami i wynikami: achieve a goal, achieve success. Rzeczownik: achievement.',
    partOfSpeech: 'verb',
    level: 'B1',
  },
  {
    word: 'significant',
    meaningEn: 'large or important enough to have an effect',
    translationPl: 'znaczący, istotny',
    exampleSentence: 'There was a significant improvement in his results.',
    explanation: 'Mocniejsze niż "big" w kontekście formalnym. Przysłówek: significantly.',
    partOfSpeech: 'adjective',
    level: 'B1',
  },
  {
    word: 'to require',
    meaningEn: 'to need something, or to make something necessary',
    translationPl: 'wymagać',
    exampleSentence: 'This job requires three years of experience.',
    explanation: 'Formalniejsze od "need". Rzeczownik: requirement (wymóg).',
    partOfSpeech: 'verb',
    level: 'B1',
  },
  {
    word: 'opportunity',
    meaningEn: 'a situation that makes it possible to do something',
    translationPl: 'okazja, możliwość',
    exampleSentence: 'This is a great opportunity to practise English.',
    explanation: 'Uwaga: "opportunity" to szansa na zrobienie czegoś, a "occasion" to okoliczność lub wydarzenie.',
    partOfSpeech: 'noun',
    level: 'B1',
  },
  {
    word: 'to consider',
    meaningEn: 'to think carefully about something before deciding',
    translationPl: 'rozważać',
    exampleSentence: 'I am considering a new job.',
    explanation: 'Po "consider" czasownik ma formę -ing: I am considering changing jobs (nie "to change").',
    partOfSpeech: 'verb',
    level: 'B1',
  },
];

export const STARTER_GRAMMAR: StarterCard[] = [
  {
    word: 'Present Simple - twierdzenia',
    meaningEn: 'Subject + verb (he / she / it adds -s or -es)',
    translationPl: 'podmiot + czasownik (+ -s w 3. os. l. poj.)',
    exampleSentence: 'She works in an office.',
    explanation:
      'Końcówkę -s dodajemy tylko w 3. osobie liczby pojedynczej. Po -s, -ss, -sh, -ch, -x, -o dodajemy -es: he watches, she goes.',
    partOfSpeech: null,
    level: 'A1',
  },
  {
    word: 'Present Simple - pytania',
    meaningEn: 'Do / Does + subject + base verb?',
    translationPl: 'Do/Does + podmiot + bezokolicznik?',
    exampleSentence: 'Do you work here? / Does she work here?',
    explanation:
      'Po "does" czasownik traci końcówkę -s, bo przeniosła się do operatora: "Does she work?" - nie "Does she works?".',
    partOfSpeech: null,
    level: 'A1',
  },
  {
    word: 'Present Simple - przeczenia',
    meaningEn: 'Subject + do not / does not + base verb',
    translationPl: 'podmiot + do not/does not + bezokolicznik',
    exampleSentence: 'I do not work here. / He does not work here.',
    explanation:
      'Formy skrócone: don’t i doesn’t. Tak jak w pytaniach, czasownik główny zostaje w formie podstawowej.',
    partOfSpeech: null,
    level: 'A1',
  },
  {
    word: 'Przedimki a / an',
    meaningEn: '"a" before a consonant sound, "an" before a vowel sound',
    translationPl: '"a" przed spółgłoską, "an" przed samogłoską',
    exampleSentence: 'a car, a university - an apple, an hour',
    explanation: 'Decyduje wymowa, nie pisownia: "a university" (bo /juː/), ale "an hour" (bo "h" jest nieme).',
    partOfSpeech: null,
    level: 'A1',
  },
  {
    word: 'Liczba mnoga rzeczowników',
    meaningEn: 'Add -s, or -es after -s, -ss, -sh, -ch, -x, -o',
    translationPl: 'końcówka -s, a po -s, -ss, -sh, -ch, -x, -o końcówka -es',
    exampleSentence: 'bus - buses, box - boxes, city - cities',
    explanation:
      'Rzeczowniki na spółgłoskę + y zmieniają y na -ies: city - cities. Formy nieregularne: child - children, man - men.',
    partOfSpeech: null,
    level: 'A1',
  },
  {
    word: 'Past Simple - czasowniki regularne',
    meaningEn: 'Subject + verb + -ed',
    translationPl: 'podmiot + czasownik z końcówką -ed',
    exampleSentence: 'I worked yesterday.',
    explanation:
      'Forma jest taka sama dla wszystkich osób. W pytaniach i przeczeniach używamy "did" + bezokolicznik: Did you work?',
    partOfSpeech: null,
    level: 'A2',
  },
  {
    word: 'Past Simple - czasowniki nieregularne',
    meaningEn: 'Subject + second form of the verb (V2)',
    translationPl: 'podmiot + druga forma czasownika',
    exampleSentence: 'I went home early.',
    explanation:
      'Drugiej formy trzeba się nauczyć na pamięć: go - went, see - saw, buy - bought. Po "did" wraca bezokolicznik: Did you go?',
    partOfSpeech: null,
    level: 'A2',
  },
  {
    word: 'Stopień wyższy przymiotnika',
    meaningEn: 'short adjective + -er, or more + long adjective',
    translationPl: 'krótki przymiotnik + -er, dłuższy z "more"',
    exampleSentence: 'bigger, happier - more interesting, more expensive',
    explanation: 'Jedna sylaba - końcówka -er. Trzy sylaby i więcej - "more". Nieregularne: good - better, bad - worse.',
    partOfSpeech: null,
    level: 'A2',
  },
  {
    word: 'Stopień najwyższy przymiotnika',
    meaningEn: 'the + adjective + -est, or the most + adjective',
    translationPl: 'the + przymiotnik + -est albo the most + przymiotnik',
    exampleSentence: 'the biggest city, the most interesting book',
    explanation: 'Przedimek "the" jest obowiązkowy. Nieregularne: good - the best, bad - the worst.',
    partOfSpeech: null,
    level: 'A2',
  },
  {
    word: 'Future: "going to"',
    meaningEn: 'Subject + am / is / are + going to + base verb',
    translationPl: 'podmiot + am/is/are + going to + bezokolicznik',
    exampleSentence: 'I am going to travel next summer.',
    explanation:
      'Używamy do planów podjętych przed rozmową i do przewidywań opartych na tym, co widzimy: It is going to rain.',
    partOfSpeech: null,
    level: 'A2',
  },
  {
    word: 'Present Perfect - budowa',
    meaningEn: 'Subject + have / has + past participle (V3)',
    translationPl: 'podmiot + have/has + trzecia forma czasownika',
    exampleSentence: 'I have finished my work.',
    explanation:
      'W 3. osobie liczby pojedynczej używamy "has". Trzecia forma: regularne z -ed, nieregularne z tabeli (do - done).',
    partOfSpeech: null,
    level: 'B1',
  },
  {
    word: 'Present Perfect czy Past Simple?',
    meaningEn: 'result that matters now vs. a finished moment in the past',
    translationPl: 'skutek teraz kontra konkretny moment w przeszłości',
    exampleSentence: 'I have lost my keys. - I lost my keys yesterday.',
    explanation: 'Gdy w zdaniu jest określony czas przeszły (yesterday, in 2019, last week), musi być Past Simple.',
    partOfSpeech: null,
    level: 'B1',
  },
  {
    word: 'First Conditional',
    meaningEn: 'If + Present Simple, will + base verb',
    translationPl: 'If + Present Simple, will + bezokolicznik',
    exampleSentence: 'If it rains, I will stay home.',
    explanation: 'Dotyczy realnych sytuacji w przyszłości. W części z "if" nigdy nie stawiamy "will".',
    partOfSpeech: null,
    level: 'B1',
  },
  {
    word: 'Strona bierna - czas teraźniejszy',
    meaningEn: 'Subject + am / is / are + past participle (V3)',
    translationPl: 'podmiot + am/is/are + trzecia forma czasownika',
    exampleSentence: 'English is spoken all over the world.',
    explanation:
      'Używamy, gdy ważniejsza jest czynność niż wykonawca. Wykonawcę dodajemy z "by": The letter is written by Anna.',
    partOfSpeech: null,
    level: 'B1',
  },
  {
    word: 'Mowa zależna - cofanie czasów',
    meaningEn: 'Present - Past, Past - Past Perfect, will - would',
    translationPl: 'teraźniejszy - przeszły, przeszły - zaprzeszły, will - would',
    exampleSentence: '"I am tired," she said. - She said she was tired.',
    explanation: 'Zmieniają się też zaimki i okoliczniki czasu: today - that day, tomorrow - the next day.',
    partOfSpeech: null,
    level: 'B1',
  },
];

export const STARTER_TENSES: StarterCard[] = [
  {
    word: 'Present Simple - zastosowanie',
    meaningEn: 'routines, habits, general facts and timetables',
    translationPl: 'rutyna, przyzwyczajenia, fakty, rozkłady jazdy',
    exampleSentence: 'The train leaves at 6 a.m. every day.',
    explanation: 'Opisuje to, co dzieje się regularnie albo jest zawsze prawdziwe - nie to, co dzieje się w tej chwili.',
    partOfSpeech: null,
    level: 'A1',
  },
  {
    word: 'Present Simple - słowa kluczowe',
    meaningEn: 'always, usually, often, sometimes, never, every day',
    translationPl: 'zawsze, zwykle, często, czasami, nigdy, codziennie',
    exampleSentence: 'She usually works from home on Fridays.',
    explanation: 'Przysłówki częstotliwości stoją przed czasownikiem głównym, ale po "to be": She is always late.',
    partOfSpeech: null,
    level: 'A1',
  },
  {
    word: 'Present Continuous - budowa',
    meaningEn: 'Subject + am / is / are + verb + -ing',
    translationPl: 'podmiot + am/is/are + czasownik z -ing',
    exampleSentence: 'I am reading a book right now.',
    explanation: 'Przy dodawaniu -ing: nieme -e znika (make - making), a krótka samogłoska podwaja spółgłoskę (sit - sitting).',
    partOfSpeech: null,
    level: 'A1',
  },
  {
    word: 'Present Continuous - zastosowanie',
    meaningEn: 'actions happening now, temporary situations, fixed plans',
    translationPl: 'czynność teraz, sytuacja tymczasowa, ustalony plan',
    exampleSentence: 'I am meeting my dentist on Monday.',
    explanation: 'Czasowników stanu (know, like, want, believe) zwykle nie używamy w tej formie.',
    partOfSpeech: null,
    level: 'A2',
  },
  {
    word: 'Present Perfect - zastosowanie',
    meaningEn: 'finished actions with a result now, and life experience',
    translationPl: 'czynność zakończona ze skutkiem teraz, doświadczenia życiowe',
    exampleSentence: 'I have broken my phone, so I cannot call you.',
    explanation: 'Nie podajemy, kiedy dokładnie coś się stało - liczy się to, co z tego wynika teraz.',
    partOfSpeech: null,
    level: 'B1',
  },
  {
    word: 'Present Perfect - słowa kluczowe',
    meaningEn: 'just, already, yet, ever, never, since, for',
    translationPl: 'właśnie, już, jeszcze, kiedykolwiek, nigdy, od, przez',
    exampleSentence: 'I have lived here for five years.',
    explanation: '"since" wskazuje początek okresu (since 2019), a "for" jego długość (for five years).',
    partOfSpeech: null,
    level: 'B1',
  },
  {
    word: 'Present Perfect Continuous',
    meaningEn: 'Subject + have / has + been + verb + -ing',
    translationPl: 'podmiot + have/has + been + czasownik z -ing',
    exampleSentence: 'I have been learning English for three years.',
    explanation: 'Podkreśla czas trwania czynności, która wciąż trwa lub właśnie się skończyła.',
    partOfSpeech: null,
    level: 'B2',
  },
  {
    word: 'Past Simple - zastosowanie',
    meaningEn: 'completed actions at a specific time in the past',
    translationPl: 'czynność zakończona w określonym momencie w przeszłości',
    exampleSentence: 'I visited Rome in 2019.',
    explanation: 'Typowe określenia czasu: yesterday, last week, two years ago, in 2019.',
    partOfSpeech: null,
    level: 'A2',
  },
  {
    word: 'Past Continuous',
    meaningEn: 'Subject + was / were + verb + -ing',
    translationPl: 'podmiot + was/were + czasownik z -ing',
    exampleSentence: 'I was cooking when you called.',
    explanation: 'Opisuje tło zdarzeń: dłuższa czynność w tle (Past Continuous) zostaje przerwana krótszą (Past Simple).',
    partOfSpeech: null,
    level: 'B1',
  },
  {
    word: 'Past Perfect',
    meaningEn: 'Subject + had + past participle (V3)',
    translationPl: 'podmiot + had + trzecia forma czasownika',
    exampleSentence: 'The film had already started when we arrived.',
    explanation: 'Pokazuje, że jedna czynność przeszła wydarzyła się przed inną czynnością przeszłą.',
    partOfSpeech: null,
    level: 'B2',
  },
  {
    word: 'Future Simple (will)',
    meaningEn: 'Subject + will + base verb',
    translationPl: 'podmiot + will + bezokolicznik',
    exampleSentence: 'I will help you with the report.',
    explanation: 'Używamy do decyzji podjętych w chwili mówienia, obietnic i propozycji - inaczej niż "going to".',
    partOfSpeech: null,
    level: 'A2',
  },
  {
    word: 'Future: will czy going to?',
    meaningEn: 'will = decision made now, going to = plan made earlier',
    translationPl: 'will = decyzja teraz, going to = plan z wcześniej',
    exampleSentence: 'The phone is ringing - I will get it. / I am going to call her tonight.',
    explanation: 'Przy przewidywaniach opartych na dowodach wybieramy "going to": Look at those clouds - it is going to rain.',
    partOfSpeech: null,
    level: 'B1',
  },
  {
    word: 'Future Continuous',
    meaningEn: 'Subject + will + be + verb + -ing',
    translationPl: 'podmiot + will + be + czasownik z -ing',
    exampleSentence: 'At 8 p.m. tomorrow I will be flying to London.',
    explanation: 'Mówi o czynności, która będzie w trakcie w konkretnym momencie w przyszłości.',
    partOfSpeech: null,
    level: 'B2',
  },
  {
    word: 'Future Perfect',
    meaningEn: 'Subject + will + have + past participle (V3)',
    translationPl: 'podmiot + will + have + trzecia forma czasownika',
    exampleSentence: 'By next June I will have finished the course.',
    explanation: 'Opisuje czynność, która zakończy się przed danym momentem w przyszłości - stąd częste "by then", "by 2030".',
    partOfSpeech: null,
    level: 'B2',
  },
];

export const STARTER_DECKS = [
  {
    type: 'VOCABULARY' as const,
    name: 'Słownictwo - start (A1-B1)',
    description: 'Podstawowe czasowniki, rzeczowniki i przymiotniki na poziomach A1-B1, z tłumaczeniem i przykładem użycia.',
    color: '#2563EB',
    icon: null,
    cards: STARTER_VOCABULARY,
  },
  {
    type: 'GRAMMAR' as const,
    name: 'Gramatyka - start (A1-B1)',
    description: 'Najważniejsze konstrukcje gramatyczne: przedimki, liczba mnoga, stopniowanie, strona bierna, mowa zależna.',
    color: '#14B8A6',
    icon: null,
    cards: STARTER_GRAMMAR,
  },
  {
    type: 'TENSES' as const,
    name: 'Czasy angielskie - start (A1-B2)',
    description: 'Czasy teraźniejsze, przeszłe i przyszłe: budowa, zastosowanie i słowa kluczowe, które je zdradzają.',
    color: '#F59E0B',
    icon: null,
    cards: STARTER_TENSES,
  },
];
